trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerNamespace: oneapilevelzero
  dockerRepo: github-ci-cache
  dockerRepoFull: $(dockerNamespace)/$(dockerRepo)
  refSlug: $[ lower(replace(variables['Build.SourceBranch'], '/', '-')) ]

jobs:
- job: eoan
  steps:
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: DockerHub
  - task: Docker@2
    displayName: Try to pull master version of image
    inputs:
      command: pull
      arguments: $(dockerRepoFull):level-zero-toolchain-ubuntu-eoan-refs-heads-master
    continueOnError: true
  - task: Docker@2
    displayName: Try to pull prior version of image for same ref
    inputs:
      command: pull
      arguments: $(dockerRepoFull):level-zero-toolchain-ubuntu-eoan-$(refSlug)
    continueOnError: true
  - task: Docker@2
    displayName: Build container
    inputs:
      command: build
      Dockerfile: docker/build-ubuntu.Dockerfile
      repository: $(dockerRepoFull)
      tags: level-zero-toolchain-ubuntu-eoan-$(refSlug)
      arguments:
        --cache-from $(dockerRepoFull):level-zero-toolchain-ubuntu-eoan-refs-heads-master
        --build-arg IMAGE_VERSION=eoan-20200114
  - script: mkdir $(Build.Repository.LocalPath)/ccache
  - task: Cache@2
    displayName: ccache
    inputs:
      key: ccache | $(Agent.OS) | "$(Build.Repository.ID)" | $(Build.SourceVersion)
      path: $(Build.Repository.LocalPath)/ccache
      restoreKeys: ccache | $(Agent.OS) | "$(Build.Repository.ID)"
  - task: Docker@2
    displayName: CMake configure in container
    inputs:
      command: run
      arguments:
        --rm
        -v $(Build.Repository.LocalPath):$(Build.Repository.LocalPath)
        -v $(Build.BinariesDirectory):$(Build.BinariesDirectory)
        -w $(Build.BinariesDirectory)
        -e CCACHE_DIR=$(Build.Repository.LocalPath)/ccache
        -e CCACHE_BASEDIR=$(Build.Repository.LocalPath)
        $(dockerRepoFull):level-zero-toolchain-ubuntu-eoan-$(refSlug)
        cmake
          -D CMAKE_BUILD_TYPE=Release
          -D CMAKE_C_COMPILER_LAUNCHER=ccache
          -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
          $(Build.Repository.LocalPath)
  - task: Docker@2
    displayName: CMake build in container
    inputs:
      command: run
      arguments:
        --rm
        -v $(Build.Repository.LocalPath):$(Build.Repository.LocalPath)
        -v $(Build.BinariesDirectory):$(Build.BinariesDirectory)
        -w $(Build.BinariesDirectory)
        -e CCACHE_DIR=$(Build.Repository.LocalPath)/ccache
        -e CCACHE_BASEDIR=$(Build.Repository.LocalPath)
        $(dockerRepoFull):level-zero-toolchain-ubuntu-eoan-$(refSlug)
        cmake --build . --config Release
  - task: Docker@2
    displayName: CMake build packages in container
    inputs:
      command: run
      arguments:
        --rm
        -v $(Build.Repository.LocalPath):$(Build.Repository.LocalPath)
        -v $(Build.BinariesDirectory):$(Build.BinariesDirectory)
        -w $(Build.BinariesDirectory)
        -e CCACHE_DIR=$(Build.Repository.LocalPath)/ccache
        -e CCACHE_BASEDIR=$(Build.Repository.LocalPath)
        $(dockerRepoFull):level-zero-toolchain-ubuntu-eoan-$(refSlug)
        cmake --build . --config Release --target package
